export const ADD_PROPERTY = "ADD_PROPERTY";
export const ADD_PROPERTY_RECEIVED = "ADD_PROPERTY_RECEIVED";
export const ADD_PROPERTY_FAILED = "ADD_PROPERTY_FAILED";

export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
export const FETCH_PROPERTIES_RECEIVED = "FETCH_PROPERTIES_RECEIVED";

export const FETCH_STATS = "FETCH_STATS";
export const FETCH_STATS_RECEIVED = "FETCH_STATS_RECEIVED";